version: '3.7'

volumes:
  postgres_data:
    driver: local

services:
  database:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example
  adminer:
    image: adminer
    restart: always
    ports:
      - "8085:8080"